insurance_app_web/config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users, controllers: {
		registrations: 'users/registrations',
		sessions: 'users/sessions',
		omniauth_callbacks: 'users/omniauth_callbacks'
		}

  resources :policies, only: %i(index new create)
  get 'search', to: 'policies#search'

  get 'payments/success'
  get 'payments/cancel'

  mount ActionCable.server => '/cable'
  post "/transmits_police_payment_status", to: "payments#transmits_police_payment_status"

  get 'error', to: 'home#error'

  get "up" => "rails/health#show", as: :rails_health_check
end

insurance_app_web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car Insurance Web App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js", "data-turbo-track": "reload", type: "module", defer: true %>
    
  </head>

  <body class="bg-body-tertiary">
    <div class="container">
      <nav class="navbar navbar-expand-lg bg-primary bg-body-tertiary">
        <div class="container-fluid">
          <%= link_to 'Home', root_path, class: "nav-link active" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarTogglerDemo03">
            <% if user_signed_in? %>
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"></li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Policy
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Policies', policies_path, class:"dropdown-item" %></li>
                    <li><%= link_to 'New Policy', new_policy_path, class:"dropdown-item" %></li>
                  </ul>
                </li>
              </ul>
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= form_with(url: search_path, method: :get, class: "d-flex") do |f| %>
                    <%= f.text_field :search, placeholder: "Search by Policy Id", class: "form-control me-2" %>
                    <%= f.submit 'Search', class: 'btn btn-outline-secondary' %>
                  <% end %>
                </li>
              </ul>
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= current_user.email%>
                  <% if current_user.avatar_url.present? %>
                    <%= image_tag(current_user.avatar_url, class: 'avatar') %><br>
                  <% else %>
                    <%= image_tag('no_avatar.png', class: 'avatar') %><br>
                  <% end %>
                </li>
              </ul>
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item d-flex justify-content-evenly">
                  <%= button_to "Logout", destroy_user_session_path, data: {turbo: "false"}, method: :delete, class: "btn btn-secondary btn-sm" %>
                </li>
              </ul>
            <% else %>
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= button_to "Login", new_user_session_path, data: { turbo: false }, method: :get, class: "btn btn-secondary btn-sm ms-4 me-2" %>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </nav>
      <div class="text-danger text-center "><%= alert %></div>
      <div class="text-success text-center"><%= notice %></div>
      <%= yield %>
    </div>    
  </body>
</html>